server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        ip: 127.0.0.1
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由

        #Predicate测试
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
#            指定时间仅能在此时后访问，例如用于秒杀活动
#            - After=2024-06-09T09:55:25.099837100+08:00[Asia/Shanghai]
            # 指定时间之后访问，
#            - Before=2024-06-09T10:08:25.099837100+08:00[Asia/Shanghai]
#            cookie中带有指定键值对username=komikive
#            - Cookie=username, komikive
            #请求头要有X-Request-Id属性并且值为整数的正则表达式
#            - Header=X-Request-Id, \d+
#            - Host=**.komikive.com
#            - Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
#            - RemoteAddr=192.168.110.1/24    # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
#            - Method=GET,POST  #指定请求方法
            #自定义Factory
#            - Level=vip1


       #filter测试
        - id: pay_routh3 #pay_routh3
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/filter/**              # 断言，路径相匹配的进行路由
#            - Path=/XYZ/abc/{segment}           # 断言，为配合SetPath测试，{segment}的内容最后被SetPath取代

#          filters:
#            - AddRequestHeader=X-Request-atguigu1,atguiguValue1  # 请求头kv，若一头含有多参则重写一行设置
#            - AddRequestHeader=X-Request-atguigu2,atguiguValue2
#            - RemoveRequestHeader=sec-fetch-site      # 删除请求头sec-fetch-site
#            - SetRequestHeader=sec-fetch-mode, Blue

#            - AddRequestParameter=customerId,9527001 # 新增请求参数Parameter：k ，v
#            - RemoveRequestParameter=customerName   # 删除url请求参数customerName，你传递过来也是null

#            - AddResponseHeader=X-Response-atguigu, BlueResponse # 新增请求参数X-Response-atguigu并设值为BlueResponse
#            - SetResponseHeader=Date,2099-11-11 # 设置回应头Date值为2099-11-11
#            - RemoveResponseHeader=Content-Type # 将默认自带Content-Type回应属性删除

#            - PrefixPath=/pay # http://localhost:9527/pay/gateway/filter   #添加路径前缀
#            - SetPath=/pay/gateway/{segment} #设置路径 # {segment}表示占位符，你写abc也行但要上下一致
#            - RedirectTo=302, http://www.baidu.com/ # 访问http://localhost:9527/pay/gateway/filter跳转到http://www.atguigu.com/
            #自定义Filter
#            - My=komikive

